server:
  port: 8080

spring:
  application:
    name: customers-service
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 80
      minimum-idle: 70
      connection-timeout: 30000
      idle-timeout: 600000
      leak-detection-threshold: 4000
      max-lifetime: 1800000
      pool-name: HikariPool-Customer-API

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 50

  flyway:
    locations: classpath:db/migration

resilience4j:
  bulkhead:
    configs:
      default:
        maxWaitDuration: 0
    instances:
      customers-read:
        baseConfig: default
        maxConcurrentCalls: 40
      customers-write:
        baseConfig: default
        maxConcurrentCalls: 40
  ratelimiter:
    instances:
      customers-read:
        limitForPeriod: 1500
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
      customers-write:
        limitForPeriod: 1500
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  endpoints:
    web:
      exposure:
        include: health, info, metrics
    endpoint:
      health:
        show-details: always

app:
  business-timezone: "America/Sao_Paulo"