name: "Code Review"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: "Run Gemini AI Code Review"
        uses: petarzarkov/gemini-code-review-action@latest
        with:
          model: gemini-2.5-flash
          enable_conversation_context: true
          skip_draft_prs: true
          language: Portuguese (Brazil)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEYs }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKENn }}